rails_docker_app/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :bookmarks
    end
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :ranks, only:[:index]

  root to: "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'search' => 'searches#search'

  resources :notifications, only: [:index, :destroy]
end

rails_docker_app/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :user
  
  enum action_type: { commented_to_own_post: 0, liked_to_own_post: 1, bookmarked_to_own_post: 2, followed_me: 3 }
end

rails_docker_app/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @notifications = current_user.notifications.order(created_at: :desc).page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notifications = current_user.notifications.destroy_all
    redirect_to notifications_path
  end
end

rails_docker_app/app/helpers/notifications_helper.rb
module NotificationsHelper
  def transition_path(notification)
    case notification.action_type.to_sym
    when :commented_to_own_post
      post_path(notification.subject.post, anchor: "comment-#{notification.subject.id}")
    when :liked_to_own_post
      post_path(notification.subject.post)
    when :bookmarked_to_own_post
      post_path(notification.subject.post)
    when :followed_me
      end_user_path(notification.subject.follower)
    end
  end
end

rails_docker_app/app/views/notifications/_bookmarked_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.username, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_path(notification.subject.post) %>
    をお気に入りに追加しました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

rails_docker_app/app/views/notifications/_commented_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.username, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_path(notification.subject.post) %>
    にコメントしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

rails_docker_app/app/views/notifications/_followed_me.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <% if notification.subject.follower.guest? %>
      ゲストユーザー
    <% else %>
      <%= link_to notification.subject.follower.username, user_path(notification.subject.follower) %>
    <% end %>
    があなたをフォローしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

rails_docker_app/app/views/notifications/_liked_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.username, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_path(notification.subject.post) %>
    にいいねしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

rails_docker_app/app/views/notifications/index.html.erb
<h4>通知</h4>
<% if @notifications.present? %>
  <%= link_to "全削除",notification_path(@notifications), method: :delete,class:"btn btn-light" %>
  <% @notifications.each do |notification| %>
      <%= render "#{notification.action_type}", notification: notification %>
  <% end %>
<% else %>
  通知はありません
<% end %>