rails_docker_app/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :bookmarks
    end
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :ranks, only:[:index]

  root to: "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'search' => 'searches#search'

  resources :notifications, only: [:index, :destroy]
end

rails_docker_app/app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :user_id, {presence: true}
  belongs_to :user

  has_one_attached :url_image
  has_one :notification, as: :subject, dependent: :destroy

  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  scope :latest, -> { order(created_at: :desc) }  #desc = 降順
  scope :old, -> { order(created_at: :asc) }  #asc = 昇順
end

rails_docker_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = SearchPostsForm.new(search_post_params)
    posts_all = Post.all
    @posts = PostsFinder.new(@q, posts_all).execute.page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def new
    @post = Post.new
  end

  def create
    require 'open-uri'

    @post = Post.new(post_params)

    html = URI.open(@post.url).read
    doc = Nokogiri::HTML.parse(html)

    @post.url_title = doc.css('meta[property="og:title"] @content').to_s

    image = doc.css('meta[property="og:image"] @content').to_s
    @post.url_image.attach(io: URI.open(image), filename: image)

    @post.user_id = current_user.id
    @post.save
    redirect_to action: 'index'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to action: 'index',  notice: "投稿を削除しました。"
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    require 'open-uri'

    @post = Post.find(params[:id])

    html = URI.open(@post.url).read
    doc = Nokogiri::HTML.parse(html)

    @post.url_title = doc.css('meta[property="og:title"] @content').to_s

    image = doc.css('meta[property="og:image"] @content').to_s
    @post.url_image.attach(io: URI.open(image), filename: image)

    if @post.update(post_params)
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def favorites
    @posts = current_user.favorites_posts
  end

  def bookmarks
    @posts = current_user.bookmarks_posts
  end

  private
    def search_post_params
      params.fetch(:q, {}).permit(
        :title,
        :genre,
        :body,
      )
    end

    def post_params
      params.require(:post).permit(
        :title, 
        :body, 
        :genre,
        :url,
        :image,
        :image_cache,)
    end
end

rails_docker_app/app/helpers/posts_helper.rb
module PostsHelper
end

rails_docker_app/app/views/posts/_search.html.erb
<div class="search">
  <%= form_with model: @q, scope: :q, url: posts_path, method: :get, local: true do |f| %>
    <label>タイトル</label>
    <%= f.text_field :title, class: 'input-text', placeholder: '入力してください' %>
    <label>本文</label>
    <%= f.text_field :body, class: 'input-text', placeholder: '入力してください' %>

    <%= f.submit '検索' %>
    <%= link_to "検索をリセット", posts_path, class: 'btn-reset' %>
  <% end %>
</div>

rails_docker_app/app/views/posts/edit.html.erb
<h1 class="display">編集画面</h1>

<%= form_for(@post, url: post_path(@post)) do |f| %>
  <div class="display_title">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title, autofocus: true, :placeholder =>"#{@post.title}" %>
  </div>
  <div class="display_body">
    <%= f.label :本文 %><br>
    <%= f.text_area :body, :placeholder =>"#{@post.body}" %>
  </div>
  <div class="display_genre">
    <%= f.label :ジャンル %><br>
    <%= f.select :genre, [["選択して下さい"], ["生活"], ["授業"], ["技術"],["サークル"]] %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, :size => 140, id: "url"  %>
  </div>

  <div class="display_image">
    <%= f.label :image %>
    <%= f.file_field :image, class:'f-control', accept: 'image/*'%>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="display_update">
    <%= f.submit "更新" %>
  </div>
  <link rel="stylesheet" href="./app/assets/stylesheets/application.css">
<% end %>

rails_docker_app/app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KEIO CUMPAS HACK</title>
  </head>

  <div class="header">
    <%= link_to "ユーザ一覧", users_path, class: "navbar-item button is-warning is-light", id: "user_list" %>
    <%if current_user.present?%>
      <%= link_to "投稿作成", new_post_path, class: "navbar-item button is-warning is-light", id: "make_post" %>
    <% end %>
  </div>
  <body>
  <%= render 'search' %>

    <h1 class="list">投稿一覧</h1>
    <%= link_to "いいね順", ranks_path, class: "navbar-item button is-warning is-light", id: "user_list" %>
    <div>
      <table class="list_content">
        <tr>
          <th>タイトル</th>
          <th>ジャンル</th>
          <th>投稿日</th>
          <th>リンク</th>
          <th>いいね！数</th>
          <th>コメント数</th>
        </tr>
        <% @posts.each do |post| %>
          <tr>
            <td style="text-align:center;"><%= link_to post.title, post_path(post), id: "post_title" %></td>
            <td style="text-align:center;"><%= post.genre %></td>
            <td style="text-align:center;"><%= post.created_at.strftime('%Y-%m-%d') %></td>
            <td><a href="<%= post.url %>"><%= post.url %></a></td>
            <td style="text-align:center;"><%= post.favorites.count %></td>
            <td><%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %></td>
            <% if current_user.present? %>
              <%= render 'layouts/favorite_button', {post: post} %>
              <%= render 'layouts/bookmark_button', {post: post} %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="page">
    <%= paginate @posts %>
    </div>
  </body>
</html>

rails_docker_app/app/views/posts/new.html.erb
<div class="header">
  <%= link_to "ユーザ一覧", users_path, class: "navbar-item button is-warning is-light", id: "user_list_2" %>
  <%= link_to "投稿一覧", posts_path, class: "navbar-item button is-warning is-light", id: "post_list_2" %>
</div>
<%= form_with model: @post, local: true do |f| %>

  <h1 class="display">投稿作成</h1>
  <div class="display_genre"><%= f.label :ジャンル %><br>
    <%= f.select :genre, [["選択して下さい"], ["生活"], ["授業"], ["技術"],["サークル"]] %>
  </div>
  
  <div class="display_title"><%= f.label :タイトル %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="display_body"><%= f.label :本文 %><br>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, :size => 140, id: "url"  %>
  </div>
  
  <div class="display_post"><%= f.submit "投稿する" %>
  </div>
<% end %>

rails_docker_app/app/views/posts/show.html.erb
<div class="header">
  <%= link_to "投稿一覧", posts_path, class: "navbar-item button is-warning is-light", id: "posts_list" %>
  <%if current_user.present?%>
  <% if @post.user_id == current_user.id %>
    <%= link_to "編集", edit_post_path(@post), id: "edit" %>
  <% end %>
  <% end %>
</div>

<h1><%= @post.title %></h1>
<div class="post_body"><%= @post.body %></div>
<div class="delete">
  <% if current_user.present? %>
    <% if @post.user_id == current_user.id %>
      <%= button_to "削除", post_path(@post), method: :delete, data: {confirm: "投稿を削除します。よろしいですか？"} %>
    <% end %>
  <% end %>
</div>

<p><a href="<%= @post.url %>"><%= @post.url %></a></p>
<p><%= @post.url_title %></p>
<div class="">
  <%= image_tag @post.url_image.variant(resize: "200x200") %>
</div>

<div class="post_user_name"> 
  <%= link_to(@post.user.username, "/users/#{@post.user.id}")  %>さんのページ
</div>

<div>
  <p>コメント件数：<%= @post.post_comments.count %></p>
  <% @post.post_comments.each do |post_comment| %>
    <%= post_comment.user.username %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>