rails_docker_app/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :bookmarks
    end
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :ranks, only:[:index]

  root to: "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'search' => 'searches#search'

  resources :notifications, only: [:index, :destroy]
end

rails_docker_app/app/views/layouts/_bookmark_button.erb
<% if current_user.bookmark?(post) %>
  <td>
    <%= button_to 'ブックマークを外す', post_bookmark_path(post_id: post.id, id: current_user.bookmarks.find_by(post_id: post.id)), method: :delete %>
  </td>
<% else %>
  <td><%= button_to 'ブックマーク', post_bookmarks_path(post_id: post.id), method: :post %></td>
<% end %>

rails_docker_app/app/views/layouts/_favorite_button.html.erb
<% if current_user.favorite?(post) %>
  <td>
    <%= button_to 'いいね！を外す', post_favorite_path(post_id: post.id, id: current_user.favorites.find_by(post_id: post.id)), method: :delete %>
  </td>
<% else %>
  <td><%= button_to 'いいね！', post_favorites_path(post_id: post.id), method: :post %></td>
<% end %>

rails_docker_app/app/views/layouts/_header.html.erb
<div class="title">
<h1><%= link_to "KEIO CAMPUS HACK", root_path, id: "title_name" %></h1>
</div>

<div class="menu">
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-nav" %>

<% else %>
  <%= link_to "ログイン", new_user_session_path, class: "header-nav" %>
  <%= link_to "サインアップ", new_user_registration_path, class: "header-nav" %>
<% end %>
<br>
<% if current_user.present? %>
  <%= link_to "マイページ", user_path(current_user), class: "navbar-item button is-warning is-light" %>
  <%= link_to "通知一覧", notifications_path, class: "navbar-item button is-warning is-light" %>
<% end %>
</div>

rails_docker_app/app/views/layouts/_relationship_button.html.erb
<% if current_user.following?(user) %>
  <td><%= button_to 'フォローを外す', user_relationships_path(user_id: user.id), method: :delete %></td>
<% else %>
  <td><%= button_to 'フォローする', user_relationships_path(user_id: user.id), method: :post %></td>
<% end %>

rails_docker_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= yield %>
  </body>
</html>