rails_docker_app/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :posts, only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only:[:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :bookmarks
    end
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end

  resources :ranks, only:[:index]

  root to: "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'search' => 'searches#search'

  resources :notifications, only: [:index, :destroy]
end

rails_docker_app/app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notifications, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites
  has_many :favorites_posts, through: :favorites, source: :post
  has_many :bookmarks
  has_many :bookmarks_posts, through: :bookmarks, source: :post
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :post_comments, dependent: :destroy

  enum role: { general: 0, admin: 1 }

  def mine?(object)
    object.user_id == id
  end
  
  def favorite(post)
    favorites_posts << post
  end

  def unfavorite(post)
    favorites_posts.destroy(post)
  end

  def favorite?(post)
    favorites_posts.include?(post)
  end

  def bookmark(post)
    bookmarks_posts << post
  end

  def unbookmark(post)
    bookmarks_posts.destroy(post)
  end

  def bookmark?(post)
    bookmarks_posts.include?(post)
  end

  def full_name
    "#{username}"
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

rails_docker_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts

    if current_user.present?
      favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)  # ログイン中のユーザーのお気に入りのpost_idカラムを取得
      @favorite_list = Post.find(favorites)

      bookmarks = Bookmark.where(user_id: current_user.id).pluck(:post_id)
      @bookmark_list = Post.find(bookmarks)
    end

    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)

    bookmarks = Bookmark.where(user_id: @user.id).pluck(:post_id)
    @bookmark_posts = Post.find(bookmarks)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to action: 'index',  notice: "ユーザを削除しました。"
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to action: 'index'
    else
      render :new
    end
  end

  private
    def search_users_params
      params.fetch(:q, {}).permit(
        :store_name,
        :department,
        :name,
        :name_kana,
        :email,
        statuses: [],
        roles: [],
      )
    end
    
    def user_params
      params.require(:user).permit(
        :username, 
        :profile, 
        :email, 
        :role,
        :image, 
        :image_cache,)
    end
end

rails_docker_app/app/helpers/users_helper.rb
module UsersHelper
end

rails_docker_app/app/views/users/edit.html.erb
<h1 class="display">編集画面</h1>
<%= form_for(@user, url: user_path(@user)) do |f| %>
<div class="field">
  <%= f.label :email, "メールアドレス" %><br />
  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
</div>
<div class="display_username">
  <%= f.label :ユーザ名 %><br>
  <%= f.text_field :username, autofocus: true, :placeholder =>"#{@user.username}" %>
</div>
<div class="display_profile">
  <%= f.label :プロフィール %><br>
  <%= f.text_area :profile, :placeholder =>"#{@user.profile}" %>
</div>
<div class="display_profile">
  <%= f.label :管理者 %>
  <%= f.select :role, User.roles_i18n.invert, class: 'form-control' %>
</div>
<div class="display_image">
  <%= f.label :image %>
  <%= f.file_field :image, class:'f-control', accept: 'image/*'%>
  <%= f.hidden_field :image_cache %>
</div>
<div class="display_update">
  <%= f.submit "更新する" %>
</div>
<% end %>

rails_docker_app/app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
  <div class="header">
    <%= link_to "投稿一覧", posts_path, class: "navbar-item button is-warning is-light", id: "user_list_4" %>
    </div>
    <h1 class="display">ユーザ一覧</h1>
    <table class="list_content">
      <tr>
        <th>ユーザ名</th>
        <th>メールアドレス</th>
        <th>登録日</th>
        <th>更新日</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td style="text-align:center;"><%= link_to user.username, user_path(user) %></td>
          <td style="text-align:center;"><%= user.email %></td>
          <td style="text-align:center;"><%= user.created_at.strftime('%Y年%m月%d日') %></td>
          <td style="text-align:center;"><%= user.updated_at.strftime('%Y年%m月%d日') %></td>
          <td style="text-align:center;"><%= image_tag user.image.url, size: '300x230', class:'card-img-top object-fit-cover' %></td>
          <% if current_user.present? && current_user!=user %>
            <%= render 'layouts/relationship_button', {user: user} %>
          <% end %>
        </tr>
      <% end %>
    </table>
  </body>
  <%= paginate @users %>
</html>

rails_docker_app/app/views/users/show.html.erb
<div class="header">
  <%= link_to "投稿一覧", posts_path, class: "navbar-item button is-warning is-light", id: "post_list_5" %>
  <%= link_to "ユーザ一覧", users_path, class: "navbar-item button is-warning is-light", id: "user_list_5" %>
  <%if current_user.present?%>
  <% if @user.id == current_user.id %>
    <%= link_to "編集", edit_user_path(@user), id: "header_edit" %>
  <% end %>
  <% end %>
</div>

<div class="display_username">ユーザ名:<%= @user.username %></div>
<div class="display_mail">メールアドレス:<%= @user.email %></div>
<div class="display_profile">プロフィール:<%= @user.profile %></div>
<div class="display_username">フォロー:<%= @user.followings.count %></div>
<div class="display_username">フォロワー:<%= @user.followers.count %></div>

<div class="display_delete">
  <% if current_user.present? %>
    <% if @user.id == current_user.id %>
    <%= button_to "削除", user_path(@user), method: :delete, data: {confirm: "投稿を削除します。よろしいですか？"} %>
    <% end %>
  <% end %>
</div>

<div>
  <h1 class="list">いいね！した投稿</h1>
  <table class="list_content">
    <tr>
      <th>タイトル</th>
    </tr>
    <% @favorite_posts.each do |post| %>
      <tr>
        <td style="text-align:center;"><%= link_to post.title, post_path(post), id: "post_title_2" %></td>
      </tr>
    <% end %>
  </table>
</div>

<div>
  <h1 class="list">ブックマークした投稿</h1>
  <table class="list_content">
    <tr>
      <th>タイトル</th>
    </tr>
    <% @bookmark_posts.each do |post| %>
      <tr>
        <td style="text-align:center;"><%= link_to post.title, post_path(post), id: "post_title_2" %></td>
      </tr>
    <% end %>
  </table>
</div>